CREATE TABLE tracks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER 
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    title TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    visible BOOLEAN NOT NULL,
    tempo INTEGER NOT NULL,
    sequence_length INTEGER NOT NULL,
    audio_sequence TEXT ARRAY[4],
    step_sequence INTEGER ARRAY[4]
);