CREATE TABLE compositions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER 
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    title TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    public BOOLEAN NOT NULL,
    tempo INTEGER NOT NULL,
    sequence_length INTEGER NOT NULL,
    sequence_hihat INTEGER ARRAY,
    sequence_clap INTEGER ARRAY,
    sequence_trap INTEGER ARRAY,
    sequence_bass INTEGER ARRAY,
    mp3 TEXT

    -- user_id INTEGER 
    --     REFERENCES users(id) ON DELETE CASCADE NOT NULL
);